###
POST http://localhost:PORT/api
Content-Type: application/json

{

    "question": "What is Ethereum?"

}

###
POST http://localhost:PORT/gpt
Content-Type: application/json

{

    "question": "What is Bitcoin?"
    
}
